parameters:
  agent_name: er_cifar
  batch_size: 128
  data_order: fixed
  epochs: 70
  filename: er_cifar100_with_miro_
  get_history: false
  load_from_history: false
  graph: false
  mode: disjoint
  model: resnet32
  num_task_cls_per_task:
  - - 10
    - 10
  num_workers: 2
  rb_path: data/cl_saved_data/cifar100/fixed/
  rb_size: 2000
  result_save_path: results_test/cifar100/
  run: 1
  sampling: ringbuffer
  save_final_model: false
  checkpoint_path: ./saved_checkpoints/
  save_tasks: true
  saver: true
  seed_start: 0
  st_size: 5000
  swap: true
  swap_base: random
  swap_period: 1
  test_set: cifar100
  test_set_path: data/cifar-100-python
  threshold:
  - 1
  jetson: false
  optimizer:
    ckpt_size: 10
    configs: balanced
    cutline: 0.5
    data_ratio: 0.05
    navi_policy:
    - grid
    - none
    pretrain: false
    score_policy: highest_ETA
    seed: 0
    start_point: 6
    trail_duration: 5
    use_ckpt: true